### ISSUE TITLE
DEA ignores environment variables with bracket characters in them

### ISSUE THREAD

**Issue by gberche-orange** [cloudfoundry/dea_ng#197]
An environment variable set with a bracket character in its name is currently refused by DEA both at staging and running stages 

```
$ cf set-env hello-world 'SERVICES[ID]_METADATA_LONG_DESCRIPTION' 'a desc'
$ cf restage hello-world
Restaging app hello-world in org [..] / space [..;] as [...]...
-----> Downloaded app package (4.0K)
-----> Downloaded app buildpack cache (4.0K)
[...]
/bin/bash: line 7: export: `SERVICES[ID]_METADATA_LONG_DESCRIPTION=a desc': not a valid identifier
[...]
```

This does not fail the staging/running though, and requires careful inspection of the output logs to diagnose.

This reproduces with DEA shipped in cf-release v237.
This problem isn't present with diego version recommended with v237

This syntax is quite useful to be able to use environment variables with brackets in them, as this format is natively interpreted by spring boot for loading [configuration properties with arrays and maps](http://docs.spring.io/spring-boot/docs/current/reference/html/boot-features-external-config.html#boot-features-external-config-loading-yaml)

Usage of this format may increase with potential native usage suggested in https://github.com/spring-cloud/spring-cloud-cloudfoundry-service-broker/issues/11#issue-153739842

**Comment by ScarletTanager** [comment]
Hi @gberche-orange ,

Unfortunately, this is not an issue with our code - it is simply the way that `bash` does variable expansion.  Specifically, `bash` does not allow square brackets in variable names.  Diego allows you to inject variables with square brackets because it does not pass them directly into the shell, but you still cannot read those variables or their values using Diego even though they may appear to have been set.  Diego's backend of `garden-linux` uses bash, just as we do.

We are closing the issue at this time - there is really nothing we could do to support this.

Thank you,

@ScarletTanager & @jberkhahn , CF RuntimeOG Team

**Comment by gberche-orange** [comment]
Hi @ScarletTanager and @jberkhahn for your response.

I understand Diego indeed propagates such env vars with bracket characters in them, and apps are able to read them.

Here is a procedure I use to test it with a sample java application

```
$ git clone https://github.com/s-bortolussi/env-properties-demo.git
$ mvn build
$ cf push demo-env --no-start
$ cf set-env hello-world 'SERVICES[ID]_METADATA_LONG_DESCRIPTION' 'a desc'
$ cf start demo-env
$ cf curl <route>/env
```

Output of /env endpoint indeed displays the environment var being exported with bracket char in them:

```
systemEnvironment": {
[...]
    "SERVICES[ID]_METADATA_LONG_DESCRIPTION": "a desc",
[...]
```

We should also be able to verify the env var was probably set through ``cf ssh`` and display output of ``cat /proc/pid/environ`` to rule out any java-level transformation of this env var.

As described into http://stackoverflow.com/questions/2821043/allowed-characters-in-linux-environment-variable-names brackets in env name is supported at the OS level (and hence could be supported in containers such as CF apps), but not supported in a standard way by shells such as bash.

I'm not sure how diego currently handles the environment variable setting to apparently not be affected by the bash limitation.

It might be interesting for DEAs though to fail on the rejected environment variable export, rather than simply display the error trace and proceed.

As a final note, I realize such unusual variable names are however not very portable (e.g. when running the same app on a local development box outside CF, bash would reject it), so we'll try to find a more portable environment variable format for our use case (https://github.com/Orange-OpenSource/static-creds-broker/issues/27 )

**Comment by ScarletTanager** [comment]
Hi @gberche-orange ,

An issue for us is that we cannot support something which is language-specific - for example, you could probably also read this variable in a golang app using Diego as well.  But whether or not the OS supports it (the OS does not do the variable interpolation, that's normally done by the shell, in our case /bin/bash, AFAIK), the shell does not, and that means that, even were we to figure out a way to set the variable, any app which relied on reading the variable via the shell would not be able to access it.  We tried your example of doing a cf ssh and then checking that we could read the variable, and this failed, since it relies on the shell's ability to do variable interpolation and expansion.  So as you note, it's as much about portability as anything.  I am anything but a Spring expert, but I'm pretty sure you'll be able to find something more portable fairly quickly.

We do appreciate your input, and we do wish we had a "happier" answer.

Best,

@ScarletTanager, CF RuntimeOG team
