### ISSUE TITLE
drain too slow

### ISSUE THREAD

**Issue by shijiaxin** [cloudfoundry/dea_ng#199]
my cf version is 238
It takes about 10 minutes to stop a runner using bosh 
I check the drain script, found following 2 lines: 
timeout=601
countdown=$(( $timeout * 10 ))

But when I check the drain log, there is something like this
drain triggered for 8889
.................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................Drained

So it seems that it spend a lot of time draining, but finally it succeed.

So there is no timeout? why it's so slow?

my runner has 2 instances running on it. During this 10 munutes, I use cf app my-app to check the status of the instance, and found that one instance is down , and another instance is running (at another VM). 

Can anyone explain why ?

**Comment by shijiaxin** [comment]
I continue to check , and found that hm9000_sender is running ,but doesn't generate any log. it's quite wield.

**Comment by ScarletTanager** [comment]
Hi @shijiaxin,

It looks like this issue is resolved in cf-release v239. CF v238 is missing this [commit](https://github.com/cloudfoundry/hm9000/commit/069863870c6c4d725c4df7fcdefba8b4b487bfad) and CC is missing the associated [commit](https://github.com/cloudfoundry/cloud_controller_ng/commit/9475adea9f1dca332a163a106573a473b0716b97).

We are going to close out this issue. If you have any additional concerns feel free to reopen.

Thanks,
@ScarletTanager & @DanLavine,
RuntimeOG Team
